#!/bin/bash
#v1.6 by bobo3769


#============================================#
#                  ╔═╗╔═╗╔╦╗                 #
#                  ╚═╗║╣  ║                  #
#                  ╚═╝╚═╝ ╩                  #
#============================================#
#設定的部分

#your domain. ex.:"yourdomain.net"
#你的域名是什麼呢？例如:"yourdomain.net"
domain="yourdomain.net"

#host name with what you want. ex."test" its mean "test.yourdomain.net."
#use "@" for root
#主機名稱要用什麼呢？例如:"test"表示 "test.yourdomain.net"
#使用"@"作為根...阿就是"yourdomain.net"的意思
hostname="@"

# the API key generated by godaddy
#[API_KEY]:[API_SECRET]
#使用godaddy給你的API key呀
#格式在上面啦
apikey="yourAPIkey:APIsecret"

#how often do you want to check again?
#多久要檢查一次呢？
againtime=60m




#============================================#
#   ╔╦╗╔═╗╔╗╔/╔╦╗  ╔╦╗╔═╗╦ ╦╔═╗╦ ╦  ╔╦╗╔═╗   #
#    ║║║ ║║║║  ║    ║ ║ ║║ ║║  ╠═╣  ║║║║╣    #
#   ═╩╝╚═╝╝╚╝  ╩    ╩ ╚═╝╚═╝╚═╝╩ ╩  ╩ ╩╚═╝   #
#============================================#
#DO NOT CHANGE anything after this line if you dont know what you do
#在這行之後別碰我呀 除非你清楚你正在做什麼

echo "         ____  ____  _   _______"
echo "        / __ \/ __ \/ | / / ___/"
echo "       / / / / / / /  |/ /\__ \ "
echo "      / /_/ / /_/ / /|  /___/ / "
echo "     /_____/_____/_/ |_//____/  "
echo "                      on godaddy"
echo "                                "

# loop
while [ 1 = 1 ]
     do
     #getip
     myip=`curl -s "https://api.ipify.org"`
     dnsget=`curl -s -X GET -H "Authorization: sso-key ${apikey}" "https://api.godaddy.com/v1/domains/${domain}/records/A/${hostname}"`
     dnsip=`echo $dnsget | cut -d ',' -f 1 | tr -d '"' | cut -d ":" -f 2`

     #say
	 echo "    ________________________________________  "
         echo "  / \                                       \ "
	 echo " |   |            DDNS on godaddy           | "
         echo "  \_ |  Domain:   $hostname.$domain"
         echo "     |                                      | "
	 echo "     |  Myip is $myip "
         echo "     |                                      | "
         echo "     |  DNS record is $dnsip "
         echo "     |                                      | "
         echo "     |                                      | "

     #put
     if [ "$myip" = "$dnsip" ]
         then
         echo "     |                                      | "
	 echo "     |  Nothing Change.                     | "
	 echo "     |                                      | "
         else
             curl -s -X PUT "https://api.godaddy.com/v1/domains/${domain}/records/A/${hostname}" -H "Authorization: sso-key ${apikey}" -H "Content-Type: application/json" -d "[{\"data\": \"${myip}\"}]"
	echo "     |                                      | "
	echo "     |   IP record change!                  | "
	echo "     |                                      | "
	 fi
	 #time
	echo "     |   waitting for "$againtime""
	echo "     |                                      | "
	y=`date +%Y`
	m=`date +%m`
	d=`date +%d`
	hr=`date +%H`
	min=`date +%M`
	sec=`date +%S`
	echo "     |              $y/$m/$d  $hr:$min:$sec"
	echo "     |   ___________________________________|___ "
	echo "     |  /                                      / "
	echo "     \_/______________________________________/ "
     sleep $againtime
done
